/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Logging.ThriftContract
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TLogPackage : TBase
  {
    private long _IP;
    private int _AppId;
    private List<TLogEntity> _Items;

    public long IP
    {
      get
      {
        return _IP;
      }
      set
      {
        __isset.IP = true;
        this._IP = value;
      }
    }

    public int AppId
    {
      get
      {
        return _AppId;
      }
      set
      {
        __isset.AppId = true;
        this._AppId = value;
      }
    }

    public List<TLogEntity> Items
    {
      get
      {
        return _Items;
      }
      set
      {
        __isset.Items = true;
        this._Items = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool IP;
      public bool AppId;
      public bool Items;
    }

    public TLogPackage() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              IP = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              AppId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.List) {
              {
                Items = new List<TLogEntity>();
                TList _list5 = iprot.ReadListBegin();
                for( int _i6 = 0; _i6 < _list5.Count; ++_i6)
                {
                  TLogEntity _elem7;
                  _elem7 = new TLogEntity();
                  _elem7.Read(iprot);
                  Items.Add(_elem7);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("TLogPackage");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.IP) {
        field.Name = "IP";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(IP);
        oprot.WriteFieldEnd();
      }
      if (__isset.AppId) {
        field.Name = "AppId";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(AppId);
        oprot.WriteFieldEnd();
      }
      if (Items != null && __isset.Items) {
        field.Name = "Items";
        field.Type = TType.List;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Items.Count));
          foreach (TLogEntity _iter8 in Items)
          {
            _iter8.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("TLogPackage(");
      bool __first = true;
      if (__isset.IP) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("IP: ");
        __sb.Append(IP);
      }
      if (__isset.AppId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("AppId: ");
        __sb.Append(AppId);
      }
      if (Items != null && __isset.Items) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Items: ");
        __sb.Append(Items);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
